### ISSUE TITLE
The location of the links.txt file is too rigid

### ISSUE THREAD

**Issue by cptanalatriste** [danikgan/COMP0138#1]
After running the Script on an Ubuntu system using IntelliJIDEA, I obtained the following prompt:

```
Hello World!

Specify the path for the text document, containing links and their corresponding number of commits to download. State the folders after: 
/Users/carlos/
```
However, on a Linux system user files are typically stored in `/home/username`. The application should be flexible enough to support an arbitrary location.

**Comment by danikgan** [comment]
Just updated it. 
Will need to add proper support for Windows.
