### ISSUE TITLE
When records.xls is written more information can be provided

### ISSUE THREAD

**Issue by cptanalatriste** [danikgan/COMP0138#5]
I'm thinking about file name and location, and number of commits included. Just as a reference

**Comment by danikgan** [comment]
Could you, please, clarify this comment for me.

Are you suggesting to have, for instance, a name of _"records-278.xlsx"_, where _"278"_ is the number of records? This will, however, require some changes to the code (not simplest). For example, when we restart the analysis after an urgent shutdown, the code will need to understand, which file to append to, even if the name is variant. Additionally, as Bugzilla part of the script requires previous output as the new input, it will also need to understand the naming conventions. 

All of this is **manageable**, but will require a precise understanding of our intentions! As frequently changing the script may introduce unnecessary bugs. So, please, describe all the additional information you would like me to add and the way you would like me to represent it, stating the priorities. I will then group them myself by tasks, which are similar or not, and will email you about how long each might take me.
